### ISSUE TITLE
OSX - Generally doesn't seem to work

### ISSUE THREAD

**Issue by warreneblackwell** [1Amir/directorycheck#1]
Default code doesn't run on my macbook, due to path which doesn't exist. 

Changing it to / root path spins the program. 

Changing it to a known, light-weight path on my machine does not seem to produce the desired output. I get:

Warrens-MacBook-Air:go dubb$ pwd
/Users/dubb/go
Warrens-MacBook-Air:go dubb$ cat amir.py 
import os

os.walk("/Users/dubb/go")
[x[0] for x in os.walk("/Users/dubb/go")]
next(os.walk('.'))[1]
print x
Warrens-MacBook-Air:go dubb$ python amir.py 
('/Users/dubb/go/src/sourcegraph.com/sqs/goreturns/returns', [], ['fix.go', 'fix_test.go', 'index.go', 'returns.go'])
Warrens-MacBook-Air:go dubb$ ls -la
total 24
drwxr-xr-x  11 dubb  staff   374 May  4 17:29 .
drwxr-xr-x+ 36 dubb  staff  1224 May  4 17:29 ..
drwxr-xr-x  15 dubb  staff   510 May  4 17:24 .git
-rw-r--r--   1 dubb  staff   266 Jan  1 14:32 .gitignore
drwxr-xr-x   4 dubb  staff   136 Jan  1 14:38 .vscode
-rw-r--r--   1 dubb  staff     4 Jan  1 14:32 README.md
-rw-r--r--   1 dubb  staff   109 May  4 17:29 amir.py
drwxr-xr-x  33 dubb  staff  1122 Jan  1 14:55 bin
drwxr-xr-x   3 dubb  staff   102 Jan  1 14:33 games
drwxr-xr-x   3 dubb  staff   102 Jan  1 14:36 pkg
drwxr-xr-x   6 dubb  staff   204 Jan  1 14:40 src

**Comment by warreneblackwell** [comment]
Do come back to this issue and close it!

**Comment by 1Amir** [comment]
Desire wise,do you want the output to be like the "ls -la" command
